// Original Finnish copy. Append entries rather than reordering the established rotation.
// A curated rotation keeps the feature available without external services or secrets.
type DailyBit = { title: string; lines: readonly string[]; tip: string };
export const DAILY_BITS: readonly DailyBit[] = [
  { title: 'Lounaan määritelmä', lines: ['Kehittäjä: ”Onko lounas valmis?”', 'Projektipäällikkö: ”Riippuu hyväksymiskriteereistä.”'], tip: 'Kirjoita ennen toteutusta yksi konkreettinen esimerkki siitä, miltä valmis lopputulos näyttää.' },
  { title: 'Toimii minun koneellani', lines: ['”Toimii minun koneellani.”', '”Hienoa. Varataanko sille paikka palvelinsalista?”'], tip: 'Liitä vikailmoitukseen ympäristö, toistovaiheet sekä odotettu ja toteutunut tulos.' },
  { title: 'Kahvin välimuisti', lines: ['Kehittäjä täyttää kahvikupin.', 'Kollega: ”Etkö juuri hakenut kahvia?”', '”Se oli välimuistissa. Tämä on tuore haku.”'], tip: 'Kun tutkit välimuistiongelmaa, tarkista ensin avain, vanhenemisaika ja se, mikä tapahtuma tyhjentää tiedon.' },
  { title: 'Pieni muutos', lines: ['”Tämä on vain yhden rivin muutos.”', '”Montako järjestelmää sillä rivillä on vastuullaan?”'], tip: 'Arvioi muutoksen vaikutus riippuvuuksista, älä muuttuneiden rivien määrästä.' },
  { title: 'Ankka päivystää', lines: ['Kehittäjä selittää ongelman kumiankalle.', 'Ankka ei sano mitään.', 'Kehittäjä: ”Hyvä huomio. Unohdin tyhjän listan.”'], tip: 'Selitä ongelma ääneen vaihe vaiheelta. Kerro myös oletukset, jotka tuntuvat itsestään selviltä.' },
  { title: 'Nimeämisen vaikeus', lines: ['Muuttujan nimi oli ensin data, sitten newData ja lopulta finalData2.', 'Tiedolla oli urakehitys. Merkitys jäi epäselväksi.'], tip: 'Nimeä muuttuja sen merkityksen mukaan: esimerkiksi pendingOrders kertoo enemmän kuin data.' },
  { title: 'Testin elämäntavoite', lines: ['Testi: ”Minä haluan joskus epäonnistua.”', 'Kehittäjä: ”Miksi?”', 'Testi: ”Muuten emme tiedä, huomaisinko mitään.”'], tip: 'Varmista kerran, että uusi testi epäonnistuu ilman korjausta. Näin tiedät sen osuvan oikeaan virheeseen.' },
  { title: 'Päivän standup', lines: ['”Eilen tutkin bugia. Tänään tutkin bugia.”', '”Onko esteitä?”', '”Bugi ei suostu yhteistyöhön.”'], tip: 'Kun jäät jumiin, kerro tiimille mitä kokeilit ja mikä havainto puuttuu seuraavaa päätöstä varten.' },
  { title: 'Dokumentin aikamatka', lines: ['README: ”Asennus on helppo.”', 'Kehittäjä: ”Tämä on selvästi historiallinen dokumentti.”'], tip: 'Kokeile asennusohjetta joskus puhtaassa ympäristössä. Korjaa ensimmäinen kohta, jossa joudut arvaamaan.' },
  { title: 'Hiljainen onnistuminen', lines: ['”Miksi lokissa on miljoona riviä?”', '”Halusin varmistaa, ettei onnistuminen jää huomaamatta.”'], tip: 'Kirjaa lokiin tapahtuma, sen tunniste ja tarpeellinen konteksti. Vältä salaisuuksia ja turhaa henkilötietoa.' },
  { title: 'Rajaton buffet', lines: ['Ohjelmoija näki kyltin ”syö niin paljon kuin jaksat”.', 'Hän kysyi heti, mikä on palvelun rate limit.'], tip: 'Mieti ulkoisille kutsuille aikakatkaisu ja hallittu virhetilanne. Odottaminen ei saa jatkua loputtomasti.' },
  { title: 'Koodikatselmoinnin sää', lines: ['”PR:ssä on enää yksi pieni pilvi.”', '”Mikä?”', '”Se tarvitsee kokonaisen uuden pilvipalvelun.”'], tip: 'Pidä katselmoitava muutos yhdessä aiheessa ja kerro kuvauksessa, miksi käyttäytymistä muutetaan.' },
  { title: 'Aikavyöhykkeen lounas', lines: ['”Palvelin sanoo, ettei vielä ole lounasaika.”', '”Palvelin ei asu Jyväskylässä.”'], tip: 'Valitse käyttäjälle näkyvän päivän aikavyöhyke erikseen. UTC-päivä ja paikallinen päivä voivat erota.' },
  { title: 'Väliaikainen ratkaisu', lines: ['”Tämä ratkaisu on väliaikainen.”', 'Viisi vuotta myöhemmin ratkaisu perehdyttää uusia työntekijöitä.'], tip: 'Liitä väliaikaiseen ratkaisuun syy ja selkeä poistamisehto. Pelkkä TODO ei kerro, milloin asiaan palataan.' },
  { title: 'Palaverin paluuarvo', lines: ['Palaveri palautti undefined.', 'Onneksi se kutsui seuraavan palaverin.'], tip: 'Päätä keskustelu kirjaamalla päätös, vastuuhenkilö ja seuraava askel.' },
  { title: 'Täydellinen varmuuskopio', lines: ['”Varmuuskopiointi toimii.”', '”Entä palautus?”', '”Älä nyt muuta vaatimuksia kesken projektin.”'], tip: 'Kokeile palautusta erillisessä testiympäristössä. Onnistunut kopiointi ei yksin varmista palautettavuutta.' },
  { title: 'Poikkeus lounaslistalla', lines: ['Tarjoilija: ”Onko erityistoiveita?”', 'Kehittäjä: ”Käsittelemättömät poikkeukset erilliseen astiaan.”'], tip: 'Näytä virhetilanteessa käyttäjälle, mitä hän voi tehdä seuraavaksi. Pelkkä virhekoodi harvoin auttaa.' },
  { title: 'Optimoinnin taika', lines: ['Kehittäjä nopeutti funktiota 50 prosenttia.', 'Koko sovellus nopeutui juuri sen verran, ettei kukaan huomannut.'], tip: 'Mittaa ensin, mihin käyttäjän odotusaika kuluu. Optimoi havaittu pullonkaula.' },
  { title: 'Git ja lounas', lines: ['”Miksi haarukoita on kaksi?”', '”Toinen on feature branch.”'], tip: 'Tarkista muutoslista ennen committia. Mukana voi olla paikallisia asetuksia tai vahingossa syntyneitä tiedostoja.' },
  { title: 'Tyhjä lautanen', lines: ['Suunnittelija: ”Miltä näkymä näyttää ilman dataa?”', 'Kehittäjä katsoo tyhjää lautastaan.', '”Yllättävän tutulta.”'], tip: 'Suunnittele tyhjälle näkymälle selitys ja hyödyllinen seuraava toiminto.' },
  { title: 'Kaksi totuutta', lines: ['”Meillä on yksi totuuden lähde.”', '”Kummassa tietokannassa?”'], tip: 'Nimeä, mikä järjestelmä omistaa tiedon. Dokumentoi myös, miten muut kopiot päivittyvät.' },
  { title: 'Salainen ainesosa', lines: ['Kokki ei paljastanut reseptinsä salaisuutta.', 'Kehittäjä nyökkäsi: ”Hyvä. Ei sitä versionhallintaankaan.”'], tip: 'Pidä tunnukset ja avaimet poissa lähdekoodista. Käytä ympäristön salaisuuksien hallintaa.' },
  { title: 'Klikkausoptimisti', lines: ['Käyttäjä painoi Tallenna-nappia viisi kertaa.', 'Sovellus sai viisi mahdollisuutta näyttää luonteensa.'], tip: 'Mieti, mitä tapahtuu saman pyynnön toistuessa. Estä tahattomat kaksoistallennukset.' },
  { title: 'Kehitysympäristön ekologia', lines: ['”Miksi sinulla on 37 välilehteä auki?”', '”Ne ovat ongelman luonnollinen elinympäristö.”'], tip: 'Kirjaa kesken jääneestä tehtävästä seuraava pieni askel ennen kuin vaihdat aihetta.' },
  { title: 'Nollan merkitys', lines: ['”Puuttuuko arvo vai onko se nolla?”', '”Kyllä.”'], tip: 'Erota puuttuva arvo, nolla ja tyhjä merkkijono. Ne voivat tarkoittaa käyttäjälle eri asioita.' },
  { title: 'Lounas sprintissä', lines: ['”Ehtiikö lounas tähän sprinttiin?”', '”Vain jos salaatti siirretään seuraavaan julkaisuun.”'], tip: 'Pilko tehtävä pieneksi kokonaisuudeksi, jonka hyöty voidaan näyttää ja tarkistaa erikseen.' },
  { title: 'Komentorivin kohteliaisuus', lines: ['Komentorivi kysyi: ”Oletko varma?”', 'Kehittäjä arvosti ensimmäistä vilpitöntä kysymystä koko päivänä.'], tip: 'Käytä tuhoaville toiminnoille esikatselua tai dry run -tilaa, jos sellainen on saatavilla.' },
  { title: 'Suuri yhdistäminen', lines: ['”Merge onnistui ilman konflikteja!”', '”Entä toiminnallisuus?”', '”Sitä Git ei kommentoinut.”'], tip: 'Ristiriidaton yhdistäminen ei takaa yhteensopivaa käytöstä. Tarkista muuttuneiden osien yhteinen toiminta.' },
  { title: 'Monitorin mittainen tauko', lines: ['Kehittäjä piti näyttötauon.', 'Hän siirtyi katsomaan kollegan näyttöä.'], tip: 'Lounastauolla voi vaihtaa hetkeksi sekä asentoa että puheenaihetta. Bugi odottaa kyllä.' },
  { title: 'Virheestä oppiminen', lines: ['”Mitä opimme tästä häiriöstä?”', '”Että kuvaajissa on muitakin värejä kuin vihreä.”'], tip: 'Kirjaa häiriön jälkeen aikajana ja yksi konkreettinen parannus. Keskity järjestelmän toimintaan, älä syylliseen.' },
  { title: 'Rajapinnan ruokalista', lines: ['”Tilasin keiton, mutta sain JSON-objektin.”', '”Se on meidän uusi palvelukerros.”'], tip: 'Kuvaa rajapinnasta onnistunut vastaus, virhevastaukset ja kenttien merkitys.' },
  { title: 'Väärä nappi', lines: ['”Käyttäjä ei voi mitenkään painaa tuosta.”', 'Käyttäjä: ”Haaste vastaanotettu.”'], tip: 'Testaa myös näppäimistöllä. Jokaisen toiminnon pitäisi olla saavutettavissa ilman hiirtä.' },
  { title: 'Riippuvuussuhde', lines: ['”Lisäsin vain yhden kirjaston.”', '”Keitä nämä 400 muuta ovat?”', '”Sen kavereita.”'], tip: 'Tarkista riippuvuuden tarve ja ylläpitotilanne ennen lisäämistä. Pieni oma ratkaisu voi joskus riittää.' },
  { title: 'Lukematon ohje', lines: ['”Kirjoitin tästä ohjeen.”', '”Missä?”', '”Ohjeen löytämisestä kertovassa ohjeessa.”'], tip: 'Linkitä ohje siihen kohtaan, jossa sitä tarvitaan. Hyväkään ohje ei auta, jos sitä ei löydy.' },
  { title: 'Testidatan päähenkilö', lines: ['Testikäyttäjä oli nimeltään Test Test.', 'Hänen osoitteensa oli Testikatu. Silti tuotannossa tuli yllätyksiä.'], tip: 'Kokeile pitkiä nimiä, ääkkösiä ja tyhjiä kenttiä. Käytä synteettistä testidataa.' },
  { title: 'Optimistinen lataus', lines: ['Latauspalkki saavutti 99 prosenttia.', 'Lopuksi se jäi pohtimaan elämän tarkoitusta.'], tip: 'Jos etenemistä ei voi mitata, älä keksi tarkkaa prosenttia. Kerro, mitä sovellus parhaillaan tekee.' },
  { title: 'Koodi kertoo miksi', lines: ['Kommentti: ”Kasvatetaan i:tä yhdellä.”', 'Koodi: i++', 'Katselmoija: ”Hyvä, olemme kaikki samaa mieltä.”'], tip: 'Kommentoi vaikeasti pääteltävä syy tai rajoite. Selkeä koodi kertoo yleensä jo, mitä tapahtuu.' },
  { title: 'Lounaan saatavuus', lines: ['”Keitto on loppu.”', '”Onko teillä fallback?”', '”Leipää.”'], tip: 'Suunnittele riippuvuuden häiriölle hyödyllinen varatila. Kerro selvästi, jos näytät vanhaa tietoa.' },
  { title: 'Täsmällinen arvio', lines: ['”Kauanko tähän menee?”', '”Kaksi tuntia, jos ymmärsin tehtävän. Kaksi päivää, jos en.”'], tip: 'Kerro arvion mukana tärkein epävarmuus. Se auttaa enemmän kuin näennäisen tarkka numero.' },
  { title: 'Järjestetty kaaos', lines: ['”Miksi tulokset vaihtavat järjestystä joka haulla?”', '”Pidämme käyttöliittymän elävänä.”'], tip: 'Määritä tuloksille vakaa järjestys, erityisesti sivutuksessa. Lisää tarvittaessa yksilöllinen tasatilanteen ratkaiseva kenttä.' },
  { title: 'Lounaspöydän integraatio', lines: ['Kaksi tiimiä sopi yhteisestä lounaasta.', 'Integraatio kaatui kentän ”milloin” eri tulkintoihin.'], tip: 'Sopikaa rajapinnan kenttien lisäksi yksiköt, aikavyöhykkeet ja puuttuvien arvojen merkitys.' },
  { title: 'Täydellinen haku', lines: ['Haku löysi kaiken.', 'Myös 8 000 asiaa, joita kukaan ei etsinyt.'], tip: 'Testaa hakua käyttäjän oikeilla termeillä ja tarkista ensimmäisten tulosten hyödyllisyys.' },
  { title: 'Versionumeron rohkeus', lines: ['”Miksi versio on 0.99.99?”', '”Ykkönen tuntuu suurelta sitoumukselta.”'], tip: 'Kerro julkaisutiedoissa käyttäjälle näkyvä muutos. Sisäinen tehtävänumero ei yksin selitä hyötyä.' },
  { title: 'Tuplavarmistus', lines: ['”Testasiko joku tämän?”', '”Luulin, että sinä.”', '”Hyvä. Meillä on siis kaksi oletusta.”'], tip: 'Nimeä tarkistukselle tekijä ja odotettu tulos. Yhteinen vastuu tarvitsee konkreettisen seuraavan teon.' },
  { title: 'Kahvikoneen SLA', lines: ['Kahvikone oli poissa käytöstä viisi minuuttia.', 'Tiimi löysi vihdoin palvelun, jonka saatavuutta kaikki seuraavat.'], tip: 'Valitse seurantaan käyttäjän kannalta tärkeä onnistuminen, älä pelkästään palvelinprosessin käynnissäoloa.' },
  { title: 'Sivuvaikutus', lines: ['”Tämä funktio vain tarkistaa hinnan.”', '”Miksi se tilasi pizzan?”'], tip: 'Erota tiedon lukeminen ja tilaa muuttavat toiminnot. Nimen pitäisi kertoa, jos kutsu aiheuttaa muutoksen.' },
  { title: 'Viestin elinkaari', lines: ['”Lähetin sen chattiin.”', '”Milloin?”', '”Jossain kahden viikon ja 900 viestin välissä.”'], tip: 'Siirrä pitkäikäinen päätös chatista löydettävään dokumenttiin ja linkitä se takaisin keskusteluun.' },
  { title: 'Pöytätesti', lines: ['”Toimiiko tämä mobiilissa?”', 'Kehittäjä siirsi kannettavan toiselle pöydälle.', '”Nyt se on ainakin liikkuva.”'], tip: 'Tarkista näkymä kapealla leveydellä ja suurennetulla tekstillä. Sisällön pitää säilyä käytettävänä molemmissa.' },
  { title: 'Rajaton uudelleenyritys', lines: ['”Palvelu ei vastaa.”', '”Kysytään siltä miljoona kertaa lisää. Se varmasti auttaa.”'], tip: 'Rajoita uudelleenyrityksiä ja lisää niiden väliin viivettä. Kaikkia virheitä ei kannata yrittää uudelleen.' },
  { title: 'Yksi lähde lisää', lines: ['”Tämä vakio on vain tässä tiedostossa.”', 'Haku löysi siitä kahdeksan erilaista versiota.'], tip: 'Etsi olemassa oleva toteutus ennen uuden lisäämistä. Yhteinen sääntö tarvitsee yhteisen ylläpitopaikan.' },
  { title: 'Lounaan lokalisointi', lines: ['”Käänsimme käyttöliittymän suomeksi.”', '”Miksi nappi menee reunan yli?”', '”Suomi ei suostunut samaan merkkibudjettiin.”'], tip: 'Varaa käyttöliittymässä tilaa eripituisille käännöksille. Älä oleta tekstin mahtuvan englannin mittoihin.' },
  { title: 'Bugin piiloleikki', lines: ['Bugi katosi heti, kun kollega tuli katsomaan.', 'Se suhtautui pariohjelmointiin erittäin vakavasti.'], tip: 'Tallenna vaikeasti toistuvan virheen tapahtuma-aika ja olosuhteet heti. Muisti on huono lokijärjestelmä.' },
  { title: 'Refaktoroinnin buffet', lines: ['”Korjaan ensin tämän yhden kohdan.”', 'Kolme tuntia myöhemmin kehittäjä nimeää koko arkkitehtuuria uudelleen.'], tip: 'Pidä toiminnallinen korjaus ja laaja siivous erillään, jos ne voi tarkistaa ja toimittaa itsenäisesti.' },
  { title: 'Käyttöoikeuksien kokki', lines: ['”Tarvitsen oikeuden nähdä ruokalistan.”', '”Annoin sinulle varmuuden vuoksi ravintolaketjun pääkäyttäjän.”'], tip: 'Anna tehtävään tarvittavat käyttöoikeudet. Helppo pääsy kaikkeen tekee myös virheistä laajempia.' },
  { title: 'Loputon lista', lines: ['”Listassa on vain muutama rivi.”', 'Tuotanto: ”Pidä kahvistani.”'], tip: 'Kokeile myös suurta tietomäärää. Tarkista, tarvitseeko näkymä sivutusta tai rajattua hakua.' },
  { title: 'Hiljainen muutos', lines: ['”En muuttanut mitään.”', '”Entä ympäristömuuttujan?”', '”Se ei ole koodia.”'], tip: 'Ota vian rajauksessa huomioon myös asetusten, datan ja riippuvuuksien muutokset.' },
  { title: 'Käyttäjän reitti', lines: ['Suunniteltu polku: A → B → C.', 'Käyttäjän polku: A → takaisin → uusi välilehti → C.'], tip: 'Testaa sivun päivitys, paluu edelliselle sivulle ja suora linkki kesken käyttötapauksen.' },
  { title: 'Vastaus löytyy', lines: ['”Löysin ratkaisun vanhasta keskustelusta!”', 'Viimeinen viesti: ”Sain toimimaan.”'], tip: 'Kun ratkaiset ongelman, kirjaa myös miten se ratkesi. Tuleva kollega saatat olla sinä.' },
  { title: 'Julkaisun laskuvarjo', lines: ['”Onko julkaisulle palautussuunnitelma?”', '”On. Toivomme kovasti, ettei sitä tarvita.”'], tip: 'Sovi ennen julkaisua, mistä ongelma huomataan ja miten edelliseen toimivaan tilaan palataan.' },
  { title: 'Lounaan prioriteetti', lines: ['Kehittäjä merkitsi lounaan kriittiseksi riippuvuudeksi.', 'Ensimmäistä kertaa koko tiimi hyväksyi priorisoinnin ilman keskustelua.'], tip: 'Ennen taukoa jätä itsellesi yksi lause: mitä teet seuraavaksi ja mistä tiedät sen onnistuneen.' },
];

export function dailyBit(date: string): DailyBit & { kind: string } {
  const time = Date.parse(`${date}T00:00:00Z`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(time) || new Date(time).toISOString().slice(0, 10) !== date) {
    throw new Error('Daily content requires a valid calendar date.');
  }
  const day = Math.floor((time - Date.UTC(2026, 8, 7)) / 86_400_000);
  const index = ((day % DAILY_BITS.length) + DAILY_BITS.length) % DAILY_BITS.length;
  const entry = DAILY_BITS[index];
  return { ...entry, kind: entry.lines.length === 3 ? 'Minisketsi' : 'Koodarivitsi' };
}
